server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://<LOKI_IP>:3100/loki/api/v1/push   # Replace with your Loki IP

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets: ["localhost"]
        labels:
          job: sample-app
          __path__: /app/logs/*.log  # Adjust the path to your log files