apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: LoadBalancer # So the deployment is Publicly Accesible
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui