### This Kubernets Manifest is All About The FEED MicroService ###

apiVersion: v1
kind: Namespace
metadata:
  name: feed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-feed-deployment
  namespace: feed
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-app
      tier: feed
  template:
    metadata:
      labels:
        app: my-app
        tier: feed
    spec:
      containers:
      - name: my-app-feed-container
        image: nginx:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: my-feed-service
  namespace: feed
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80    # The Port Exposed in the Image
  selector:
    app: my-app
    tier: feed
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feed-ingress
  namespace: feed
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /feed    # The Path for the Feed Service
        pathType: Prefix
        backend:
          service:
            name: my-feed-service     # Cart Service Name
            port:
              number: 80
