### This Kubernets Manifest is All About The LOGIN MicroService ###

apiVersion: v1
kind: Namespace
metadata:
  name: login
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-login-deployment
  namespace: login
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-app
      tier: login
  template:
    metadata:
      labels:
        app: my-app
        tier: login
    spec:
      containers:
      - name: my-app-login-container
        image: <LOGIN-IMAGE-NAME>
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: my-login-service
  namespace: login
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80    # The Port Exposed in the Image
  selector:
    app: my-app
    tier: login
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-ingress
  namespace: login
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /login    # The Path for the Login Service
        pathType: Prefix
        backend:
          service:
            name: my-login-service    # Cart Service Name
            port:
              number: 80
